# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# syntax=docker/dockerfile:1

# Build stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Install all dependencies including dev
COPY package.json tsconfig.json ./
RUN npm install --ignore-scripts

# Copy source and build
COPY src ./src
RUN npx tsc

# Runtime stage
FROM node:lts-alpine AS runtime
WORKDIR /app

# Install only production dependencies
COPY package.json ./
RUN npm install --omit=dev --ignore-scripts

# Copy build output
COPY --from=builder /app/build ./build

# Default command
CMD ["node", "build/index.js"]
